[platformio]
default_envs = codex_micro_leonardo

[env:codex_micro_leonardo]
platform = atmelavr@5.3.0
board = codex_micro_leonardo
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbmodem1101
